# -*- mode: ruby -*-
# vi: set ft=ruby :

$name = "gitlab"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define $name do |i|
    i.vm.hostname = $name
    i.vm.network "private_network", ip: "192.168.33.180"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = $name
    vb.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.host_vars = {
      $name => { "ansible_python_interpreter" => "/usr/bin/python3" }
    }

    # ansible.playbook = "../ansible/gitlab.yml"
    ansible.playbook = "../ansible/runner.yml"
  end
end
